name: inspire_me
description: A minimal app for inspire all that persons that feels frustration.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  adaptive_theme: ^3.2.0
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
    
  font_awesome_flutter: ^10.4.0
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6
  introduction_screen: ^3.1.4
  path_provider: ^2.0.14
  random_avatar: ^0.0.8
  screenshot: ^1.3.0
  shared_preferences: ^2.1.0
  showcaseview: ^2.0.0+1
  social_share: ^2.3.1
  sqflite: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true