name: inspire_me
description: A minimal app for inspire all that persons that feels frustration.

version: 1.0.0+3

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  adaptive_theme: ^3.2.0
  flutter:
    sdk: flutter
    
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^4.0.5
  google_mobile_ads: ^3.0.0
  google_nav_bar: ^5.0.6
  introduction_screen: ^3.1.4
  path_provider: ^2.0.14
  random_avatar: ^0.0.8
  screenshot: ^2.1.0
  shared_preferences: ^2.1.0
  showcaseview: ^2.0.0+1
  social_share: ^2.3.1
  sqflite: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/main_logo_sized.png"