import 'package:google_fonts/google_fonts.dart';

List<String?> styleList = [
  GoogleFonts.roboto().fontFamily,
  GoogleFonts.abel().fontFamily,
  GoogleFonts.chauPhilomeneOne().fontFamily,
  GoogleFonts.acme().fontFamily,
  GoogleFonts.lacquer().fontFamily,
  GoogleFonts.openSans().fontFamily,
  GoogleFonts.montserrat().fontFamily,
  GoogleFonts.lato().fontFamily,
  GoogleFonts.andika().fontFamily,
  GoogleFonts.oswald().fontFamily,
  GoogleFonts.raleway().fontFamily,
  GoogleFonts.ubuntu().fontFamily,
  GoogleFonts.nunito().fontFamily,
  GoogleFonts.mukta().fontFamily,
  GoogleFonts.mulish().fontFamily,
  GoogleFonts.caramel().fontFamily,
  GoogleFonts.sourceCodePro().fontFamily,
  GoogleFonts.azeretMono().fontFamily,
  GoogleFonts.tradeWinds().fontFamily,
  GoogleFonts.rocknRollOne().fontFamily,
  GoogleFonts.romanesco().fontFamily,
];
